Content-Type: multipart/mixed; boundary="------------sD9huaaMlpAnBpiD4PrOecIZ"
Message-ID: <19720317-ea1e-49de-b863-d2b86a5c954a@gmail.com>
Date: Mon, 13 Nov 2023 08:55:42 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Content-Language: en-GB
To: duytdn2806@gmail.com
From: Van Diep Bao Duy <duytdn2806@gmail.com>
Subject: Test email 01 with file

This is a multi-part message in MIME format.
--------------sD9huaaMlpAnBpiD4PrOecIZ
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

Hi Anh DuyTech


--------------sD9huaaMlpAnBpiD4PrOecIZ
Content-Type: text/plain; charset=UTF-8; name="Ex01_client.py"
Content-Disposition: attachment; filename="Ex01_client.py"
Content-Transfer-Encoding: base64

ZnJvbSBzb2NrZXQgaW1wb3J0ICoNCg0Kc2VydmVyTmFtZSA9ICcxMjcuMC4wLjEnDQpzZXJ2
ZXJQb3J0ID0gNTAwMDANCmNsaWVudFNvY2tldCA9IHNvY2tldChBRl9JTkVULCBTT0NLX1NU
UkVBTSkNCmNsaWVudFNvY2tldC5jb25uZWN0KChzZXJ2ZXJOYW1lLCBzZXJ2ZXJQb3J0KSkN
Cg0KYSA9IGlucHV0KCdJbnB1dCBhOiAnKQ0KYiA9IGlucHV0KCdJbnB1dCBiOiAnKQ0Kb3Bl
cmF0b3IgPSBpbnB1dCgnSW5wdXQgb3BlcmF0b3IgKGNhbiBiZSArLCAtLCAqLCAvKTogJykN
Cg0KbWVzc2FnZSA9IGYie2F9IHtvcGVyYXRvcn0ge2J9Ig0KDQpjbGllbnRTb2NrZXQuc2Vu
ZChtZXNzYWdlLmVuY29kZSgpKQ0KDQphbnMgPSBjbGllbnRTb2NrZXQucmVjdigxMDI0KS5k
ZWNvZGUoInV0Zi04IikNCg0KcHJpbnQoZid7YX0ge29wZXJhdG9yfSB7Yn0gPSB7YW5zfScg
KQ0KY2xpZW50U29ja2V0LmNsb3NlKCk=

--------------sD9huaaMlpAnBpiD4PrOecIZ--
